name: Wunderbar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.78632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#6c6c6c'
    - '#ababab'
    - '#fafafa'
    - '#f1ed14'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: f7aaaf17-c3f2-48bb-8e43-292931487495
    url: null
