name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4f5dab'
    - '#f04d2e'
    - '#f59180'
    - '#afafaf'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: null
    url: null
