name: null
favicon: null
layout_spectrum: 0.64081
typography_spectrum: 0.62653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4f5dab'
    - '#f04d2e'
    - '#f59180'
    - '#afafaf'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: awareness
    item: null
    url: null
