name: Wunderbar
favicon: null
layout_spectrum: 0.25143
typography_spectrum: 0.51775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#6c6c6c'
    - '#ababab'
    - '#fafafa'
    - '#f1ed14'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: 864d0030-b244-446a-a58f-b5d98ca6af81
    url: null
